done review version
vanja-cvetkovic-ey/Mission-to-Mars pull request #1
Opened 2022-08-03 08:55 UTC by vanja-cvetkovic-ey

2022-08-03 08:56 UTC, vanja-cvetkovic-ey commented
.

2022-08-03 13:52 UTC, Momir-Radovanovic-EY requested changes
Vanja, excellent work! Tested the PR locally, works as expected.

I especially liked how you managed your styles (scss, using variables, mixins, includes etc) inside the app, kudos for that.

Found only one UI bug(which is really impressive) and will share with you some best practices.

**Folder Structuring:**
- Overall good structuring but maby you can improve it a little bit more. Inside pages folder, add folders per pages. For example /pages/Home/ and inside it Home.jsx and Home.scss
- Also that for layout components
- Inside carousel folder component you have unused functioanl Dot.jsx
- In assets folder you will always see files with .svg .png .jpeg extensions but never jsx and scss. - Also you will not see svg as functional components but let it be for now. 

**Carousel:**

On mobile resolution if the image is wider(or something else ), card is outside of a layout
![image](https://user-images.githubusercontent.com/85942975/182616147-cf0914ca-28f4-434a-837b-e360696f6a7e.png)

- On first rendering Carousel Cards are loaded with first data that came from api, after few seconds it loads again with different data? Not sure why but please check that

**Other:**

- All static text that can be translated, put in constants and pull the value from there(for example your lorem ipsum on other pages, button , link text...)
- Clear all console.log-s inside the app
- Clear all errors/warnings in console
![image](https://user-images.githubusercontent.com/85942975/182619946-67c60b8a-4db6-4a28-9b77-b0be44de6d06.png)
- Clear all commented/unused codes
- Do research on async/await and try/catch block
- Logo Animation 👍 
- Css/Scss, responsive, using mixings, includes etc. 🥇 
- If you want to improve it more, you can all CSS properties set to be in Alphabetical order inside that block scope(not mandatory but good practice)

Also resolve requested changes below, before merging.

Over all good job once again 🚀

2022-08-03 13:52 UTC, Momir-Radovanovic-EY commented on mission_to_mars/src/components/carousel/Carousel.jsx
> +            {/* <div className="arrow">
Remove commented code.

2022-08-03 13:52 UTC, Momir-Radovanovic-EY commented on mission_to_mars/src/components/carousel/Carousel.jsx
> +        {/* {dots.map((dot) =>
Remove commented code.

2022-08-03 13:52 UTC, Momir-Radovanovic-EY commented on mission_to_mars/src/components/carousel/Carousel.jsx
> +            <div className="dots"></div>
you can use like this if there is no children inside it <div />

2022-08-03 13:52 UTC, Momir-Radovanovic-EY commented on mission_to_mars/src/components/carousel/Carousel.jsx
> +                  ></div>
Same here

2022-08-08 10:01 UTC, Momir-Radovanovic-EY requested changes
Hi Vanja, very good changes!
Still there is small adjustments that I want from you to do:

- Try to reorganize your imports better, group them by external/local imports and divide them by new line.
-Put all static text inside constants for translation purposes. And after import use it like: <p>{some_content}</p>

-Delete all console.logs
-Write README.md file, what the project is about and how it is used

Go through my comments inside PR and resolve that as well.

2022-08-08 12:51 UTC, Momir-Radovanovic-EY commented
Well done! 🥇

2022-08-08 12:51 UTC, merged